/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lab1;

public class App {

    public static void main(String[] args) {

        new HibernateUtil().testBasicUsage();

    }

}


